name: 'Deploy'

on:
  push:
    branches:
      - master

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")
  deploy:
    name: Deploy
    needs: [clear-cache]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}

      - name: Cache terraform
        uses: actions/cache@v3
        with:
          key: terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }}
          path: terraform/.terraform

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Deploy dev
        uses: artronics/terraform-flow-action@v1
        with:
          workspace: dev
          path: terraform
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

