name: 'Deploy'

on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: hashicorp/terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python and pip
        run: |
          apk install py3-pip
          pip install invoke

      - name: Terraform init
        run: invoke terraform-init
        working-directory: terraform

      - name: Terraform apply
        run: invoke terraform-apply --env=dev
        working-directory: terraform
