name: Post
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        with:
          delete_closed_pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
        name: check

      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pr_no::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.pr.outputs.pr_no }}
