name: Post
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Cache terraform
        uses: actions/cache@v3
        with:
          key: terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }}
          path: terraform/.terraform

      - name: terraform destroy PR deployment
        run: grunt terraform:destroy --github-context='${{ toJson(github) }}' --pr-no=${{ github.event.pull_request.number }}

      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        with:
          delete_closed_pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

