name: 'Pull Request'

on:
  push:
    branches:
      - '**'
      - '!master'


jobs:
  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest

    env:
      PR_NO: ${{ github.event.pull_request.number }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: |
          yarn install
          yarn global add grunt-cli

      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pr_no::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: grunt build
      - name: Test Grunt
        env:
          CONTEXT: ${{ toJson(github) }}
          PR_NO: ${{ steps.pr.outputs.pr_no }}
        run: grunt terraform:plan --github-context='${{ toJson(github) }}' --pr-no=${{ steps.pr.outputs.pr_no }}
