name: 'Pull Request'

on:
  pull_request:

jobs:
  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}

      - name: Cache terraform
        uses: actions/cache@v3
        with:
          key: terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }}
          path: terraform/.terraform

      - name: Install
        run: |
          yarn install
          yarn global add grunt-cli

      - name: Build
        run: grunt build

      - name: terraform init
        run: grunt terraform:init

      - name: terraform apply
        run: grunt terraform:plan --github-context='${{ toJson(github) }}' --pr-no=${{ github.event.pull_request.number }}

