name: 'Pull Request'

on:
  push:
    branches:
      - '**'
      - '!master'


jobs:
  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest

    env:
      PR_NO: ${{ github.event.pull_request.number }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: |
          yarn install
          yarn global add grunt-cli

      - name: Get Pull Request Number
        id: pr
        run: |
          echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
          echo "$(gh pr view --json number -q .number)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      - run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
        name: check

      - name: Test Grunt
        env:
          CONTEXT: ${{ toJson(github) }}
        run: |
          echo $CONTEXT
          grunt foo --github-context="$CONTEXT"
