name: 'Pull Request'

on:
  push:
    branches:
      - '**'
      - '!master'


jobs:
  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest

    env:
      PR_NO: ${{ github.event.pull_request.number }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: |
          yarn install
          yarn global add grunt-cli

      - run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
        name: check

      - name: Test Grunt
        env:
          CONTEXT: ${{ toJson(github) }}
        run: |
          echo $CONTEXT
          grunt foo --github-context="$CONTEXT"
